### ISSUE TITLE
Auth middleware error could be cleaned up

### ISSUE THREAD

**Issue by mike-odom** [Sacchiy/speech-recognition-app#42]
My earlier authMiddleware implementation shows a big nasty error when the user doesn't have an auth cookie. But this really isn't a big deal. They're just not logged in. I've toned the error down. 

See my changes here, you can copy over these changes to your repo.
https://github.com/ThatOdieGuy/student-picker-auth/commit/4dff0eef0720f0ed44f731ea14dbda392025dfc3

**Comment by Sacchiy** [comment]
authMiddleware file updated. all the functions are working exactly the same as before
